version: '3.9'

services:

  cassandra1:
    image: 'cassandra:latest'
    environment:
      - CASSANDRA_CLUSTER_NAME=test
      - CASSANDRA_SEEDS=172.18.0.10
#  this is actually hardcoded with SIMPLE Snitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - '9042:9042'
      - '9160:9160'

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: 'cassandra:latest'
    volumes:
      - ./cassandra_init:/cassandra_init/
    entrypoint: [ "bash", "/cassandra_init/init.sh" ]
